# Workflow API version
ZapOSApiVersion: v1alpha1

kind: Workflow

# List resources needed by workflow.
resources:

# A resource named `welcome` that is a public git repo. All the fields here are required except branch, which defaults to master.
- name: welcome
  type: git
  parameters:
    url: "git@github.com:theshabh58/welcome-resource.git"
    branch: "master"